import React, { RefObject, useMemo } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import packageJson from '../package.json';
import { useEffect } from 'react';
import { Button } from 'native-base';
import { Tree, NodeApi } from 'react-arborist';
import * as uuid from 'uuid';

// const myImageLoader = ({ src, width, quality }: any) => {
//   return src as string;
// };

type ITreeNodeInfo = {
  isLeaf: boolean;
  isInternal: boolean;
  data: ITreeNodeData;
  toggle: () => void;
};
type ITreeNodeData = {
  id: string;
  name: string;
  href?: string;
  target?: string;
  children?: ITreeNodeData[];
};
type ITreeNodeProps = {
  node: ITreeNodeInfo;
  style: unknown;
  dragHandle: RefObject<HTMLDivElement>;
};
function TreeNode({ node, style, dragHandle }: ITreeNodeProps) {
  const { href, target, name } = node.data;
  const link = useMemo(() => {
    if (target && href) {
      return (
        <a href={href} target={target}>
          {`${name} →`}
        </a>
      );
    }
    if (href) {
      return <Link href={href}>{`${name} →`}</Link>;
    }
    return <span>{name}</span>;
  }, [href, name, target]);
  return (
    <div style={style} ref={dragHandle} onClick={() => node.toggle()}>
      <div style={{ cursor: node.isInternal ? 'pointer' : undefined }}>
        {node.isLeaf ? '👉' : '📂'} {link}
      </div>
    </div>
  );
}

const data: ITreeNodeData[] = [
  {
    id: uuid.v4(),
    name: 'General',
    children: [
      { id: uuid.v4(), name: 'iframe', href: '/iframe' },
      { id: uuid.v4(), name: 'DeepLink', href: '/deeplink' },
      { id: uuid.v4(), name: 'DappList', href: '/dappList' },
      { id: uuid.v4(), name: 'Hardware SDK (coming soon)', href: '' },
    ],
  },
  {
    id: uuid.v4(),
    name: 'WalletConnect',
    children: [
      {
        id: uuid.v4(),
        name: 'WalletConnect V1',
        href: 'https://example.walletconnect.org',
        target: 'WalletConnectExampleV1',
      },
      {
        id: uuid.v4(),
        name: 'WalletConnect V2',
        href: 'https://react-app.walletconnect.com',
        target: 'WalletConnectExampleV2',
      },
      {
        id: uuid.v4(),
        name: 'Aptos WalletConnect',
        href: '/aptosWalletconnect',
      },
    ],
  },
  {
    id: uuid.v4(),
    name: 'Chain',
    children: [
      { id: uuid.v4(), name: 'EVM', href: '/ethereum' },
      { id: uuid.v4(), name: 'Solana', href: '/solana' },
      { id: uuid.v4(), name: 'NEAR', href: '/near' },
      {
        id: uuid.v4(),
        name: 'NEAR ref-ui',
        href: 'https://dapp-near-ref-ui.onekeytest.com',
        target: '_blank',
      },
      { id: uuid.v4(), name: 'Starcoin', href: '/starcoin' },
      { id: uuid.v4(), name: 'Aptos', href: '/aptos' },
      { id: uuid.v4(), name: 'Aptos Martian', href: '/aptosMartian' },
      { id: uuid.v4(), name: 'Conflux', href: '/conflux' },
      { id: uuid.v4(), name: 'Tron', href: '/tron' },
    ],
  },
];

const Home: NextPage = () => {
  useEffect(() => {
    void fetch(`/api/hello?_=${Date.now()}`);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Dapp Example - OneKey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Tree initialData={data}>{TreeNode as any}</Tree>
        <Button onPress={() => window.location.reload()}>refresh</Button>
      </main>

      <footer className={styles.footer}>
        <a>
          {/* eslint-disable-next-line @typescript-eslint/no-unsafe-member-access */}v
          {packageJson.version}
        </a>
        <iframe
          src="https://ghbtns.com/github-btn.html?user=OneKeyHQ&repo=cross-inpage-provider&type=star&count=true"
          frameBorder="0"
          scrolling="0"
          title="GitHub"
          height={20}
          width={100}
        />
        <a href="https://www.onekey.so" target="_blank" rel="noopener noreferrer">
          Powered by OneKey →
        </a>
      </footer>
    </div>
  );
};

export default Home;
