export const JS_BRIDGE_MESSAGE_IPC_CHANNEL = 'onekey@JS_BRIDGE_MESSAGE_IPC_CHANNEL';
export const JS_BRIDGE_MESSAGE_EXT_CHANNEL = 'onekey@JS_BRIDGE_MESSAGE_EXT_CHANNEL';
export const JS_BRIDGE_MESSAGE_EXT_PING = 'onekey@JS_BRIDGE_MESSAGE_EXT_PING';
export const JS_BRIDGE_MESSAGE_DIRECTION = {
  'HOST_TO_INPAGE': 'onekey@JS_BRIDGE_MESSAGE_DIRECTION-HOST_TO_INPAGE',
  'INPAGE_TO_HOST': 'onekey@JS_BRIDGE_MESSAGE_DIRECTION-INPAGE_TO_HOST',
};
export const EXT_PORT_CS_TO_BG = 'onekey@EXT_PORT_CS_TO_BG';
export const EXT_PORT_UI_TO_BG = 'onekey@EXT_PORT_UI_TO_BG';
export const DEBUG_LOGGER_STORAGE_KEY = '$$ONEKEY_DEBUG_LOGGER';
export const WALLET_INFO_LOACAL_KEY = 'onekey_wallet_info_local_key'