export enum IInjectedProviderNames {
  btc = 'btc',
  ethereum = 'ethereum',
  conflux = 'conflux',
  tron = 'tron',
  solana = 'solana',
  sollet = 'sollet',
  near = 'near',
  aptos = 'aptos',
  martian = 'martian',
  algo = 'algo',
  sui = 'sui',
  cardano = 'cardano',
  alephium = 'alephium',
  cosmos = 'cosmos',
  polkadot = 'polkadot',
  scdo = 'scdo',
  ton = 'ton',
  webln = 'webln',
  nostr = 'nostr',
  bfc = 'bfc',
  neo = 'neo',
  stellar = 'stellar',
  $private = '$private',
  $hardware_sdk = '$hardware_sdk',
  $walletConnect = '$walletConnect',
}

export type IInjectedProviderNamesStrings = keyof typeof IInjectedProviderNames;
